document.addEventListener('DOMContentLoaded',()=>{
const preview=document.getElementById('cvPreviewContent'),top=document.querySelector('.edbar');if(!preview||!top||document.getElementById('cvSaveProject'))return;
const KEY='celebrateVerseProjects',IDKEY='celebrateVerseActiveProject';let id=localStorage.getItem(IDKEY)||`cv-${Date.now()}`;localStorage.setItem(IDKEY,id);
const getProjects=()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(_){return[]}};
const formData=()=>Object.fromEntries([...document.querySelectorAll('#celebrationForm input,#celebrationForm textarea')].filter(x=>x.id).map(x=>[x.id,x.value]));
const save=()=>{const list=getProjects(),data={id,name:document.getElementById('personName')?.value?.trim()||'Untitled Celebration',updatedAt:new Date().toISOString(),html:preview.innerHTML,background:preview.style.background||'',form:formData()};const i=list.findIndex(x=>x.id===id);if(i>=0)list[i]=data;else list.unshift(data);try{localStorage.setItem(KEY,JSON.stringify(list.slice(0,50)))}catch(e){console.warn('Project storage full',e)}const s=document.getElementById('cvSaveStatus');if(s){s.textContent='✓ All changes saved';clearTimeout(s._t);s._t=setTimeout(()=>s.textContent='',1800)}};
const enc=o=>btoa(unescape(encodeURIComponent(JSON.stringify(o))));
const publish=()=>{save();const p=getProjects().find(x=>x.id===id);if(!p)return;const payload=enc({name:p.name,html:p.html,background:p.background,form:p.form});const url=new URL('celebration.html',location.href);url.searchParams.set('data',payload);if(navigator.clipboard)navigator.clipboard.writeText(url.href).catch(()=>{});window.prompt('Shareable celebration link:',url.href)};
const loadLib=src=>new Promise((ok,bad)=>{if(document.querySelector(`script[src="${src}"]`))return ok();const s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=bad;document.head.append(s)});
const exportImage=async type=>{try{await loadLib('https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js');const c=await html2canvas(preview,{backgroundColor:null,scale:2});const a=document.createElement('a');a.download=`celebrateverse.${type}`;a.href=c.toDataURL(type==='jpg'?'image/jpeg':'image/png',.92);a.click()}catch(e){alert('Image export needs the export helper to load.')}};
const exportPdf=async()=>{try{await loadLib('https://cdn.jsdelivr.net/npm/html2canvas@1.4.1/dist/html2canvas.min.js');await loadLib('https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js');const c=await html2canvas(preview,{scale:2}),pdf=new jspdf.jsPDF({orientation:c.width>c.height?'landscape':'portrait',unit:'px',format:[c.width,c.height]});pdf.addImage(c.toDataURL('image/png'),'PNG',0,0,c.width,c.height);pdf.save('celebrateverse.pdf')}catch(e){window.print()}};
const pbg=()=>preview.style.background||'linear-gradient(135deg,#3b0764,#831843)';
const exportZip=async()=>{try{await loadLib('https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js');const zip=new JSZip();zip.file('index.html',`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>CelebrateVerse</title><style>body{margin:0;font-family:Arial;background:#111;color:white}.celebration{max-width:900px;margin:40px auto;padding:30px;border-radius:24px;min-height:70vh}</style></head><body><main class="celebration" style="background:${pbg()}">${preview.innerHTML}</main></body></html>`);const blob=await zip.generateAsync({type:'blob'}),a=document.createElement('a');a.download='celebrateverse-website.zip';a.href=URL.createObjectURL(blob);a.click()}catch(e){alert('ZIP export could not start.')}};
top.insertAdjacentHTML('beforeend','<button id="cvSaveProject" type="button">💾 Save</button><button id="cvProjects" type="button">📁 Projects</button><button id="cvPublish" type="button">🚀 Publish</button><button id="cvPNG" type="button">PNG</button><button id="cvJPG" type="button">JPG</button><button id="cvPDF" type="button">PDF</button><button id="cvZIP" type="button">ZIP</button><span id="cvSaveStatus" role="status"></span>');
document.getElementById('cvSaveProject').onclick=save;document.getElementById('cvProjects').onclick=()=>{const list=getProjects();if(!list.length)return alert('My Projects\n\nNo saved projects yet.');const choice=window.prompt('My Projects\n\n'+list.map((x,i)=>`${i+1}. ${x.name}`).join('\n')+'\n\nEnter project number to open:');const n=Number(choice)-1;if(list[n]){id=list[n].id;localStorage.setItem(IDKEY,id);preview.innerHTML=list[n].html||'';preview.style.background=list[n].background||'';for(const [k,v] of Object.entries(list[n].form||{})){const el=document.getElementById(k);if(el)el.value=v}document.dispatchEvent(new CustomEvent('cv:projectLoaded'));window.location.reload()}};document.getElementById('cvPublish').onclick=publish;document.getElementById('cvPNG').onclick=()=>exportImage('png');document.getElementById('cvJPG').onclick=()=>exportImage('jpg');document.getElementById('cvPDF').onclick=exportPdf;document.getElementById('cvZIP').onclick=exportZip;
let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(save,700)};document.getElementById('celebrationForm')?.addEventListener('input',schedule);document.addEventListener('cv:changed',schedule);window.addEventListener('beforeunload',save);
loadLib('./editor-enhancements.js').catch(()=>{});save();
});