-- CelebrateVerse PHASE 22
-- Run this once in Supabase SQL Editor.
-- The frontend uses the existing publishable/anon key and RLS below.

create table if not exists public.cv_projects (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Untitled Celebration',
  project_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.cv_project_versions (
  id bigint generated by default as identity primary key,
  project_id text not null references public.cv_projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  project_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists cv_projects_user_updated_idx on public.cv_projects(user_id, updated_at desc);
create index if not exists cv_versions_project_created_idx on public.cv_project_versions(project_id, created_at desc);

alter table public.cv_projects enable row level security;
alter table public.cv_project_versions enable row level security;

drop policy if exists "cv_projects_select_own" on public.cv_projects;
drop policy if exists "cv_projects_insert_own" on public.cv_projects;
drop policy if exists "cv_projects_update_own" on public.cv_projects;
drop policy if exists "cv_projects_delete_own" on public.cv_projects;
drop policy if exists "cv_versions_select_own" on public.cv_project_versions;
drop policy if exists "cv_versions_insert_own" on public.cv_project_versions;

create policy "cv_projects_select_own" on public.cv_projects for select using (auth.uid() = user_id);
create policy "cv_projects_insert_own" on public.cv_projects for insert with check (auth.uid() = user_id);
create policy "cv_projects_update_own" on public.cv_projects for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "cv_projects_delete_own" on public.cv_projects for delete using (auth.uid() = user_id);

create policy "cv_versions_select_own" on public.cv_project_versions for select using (auth.uid() = user_id);
create policy "cv_versions_insert_own" on public.cv_project_versions for insert with check (auth.uid() = user_id);

-- Optional cleanup helper: keep only the newest 30 versions per project.
-- Run manually if desired, or schedule it later with Supabase Cron:
-- delete from public.cv_project_versions a
-- where a.id not in (
--   select id from public.cv_project_versions b
--   where b.project_id = a.project_id
--   order by b.created_at desc limit 30
-- );
